<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NetFix</AssemblyName>
    <RootNamespace>NetFix</RootNamespace>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <RollForward>LatestMajor</RollForward>
    <Version>1.1.5</Version>
    <AssemblyVersion>1.1.5.0</AssemblyVersion>
    <FileVersion>1.1.5.0</FileVersion>
    <Copyright>© 2024-2026 rupleide</Copyright>
    <Product>NetFix</Product>
    <Description>NetFix - GUI приложение для обхода блокировок Telegram и Discord</Description>
    <License>GPL-3.0-only</License>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Backup_18.03.2026_ 0-05\**" />
    <Page Remove="Backup_18.03.2026_ 0-05\**" />
    <None Remove="Backup_18.03.2026_ 0-05\**" />
    <EmbeddedResource Remove="Backup_18.03.2026_ 0-05\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\noise.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\noise.png" />
  </ItemGroup>

  <!-- Копируем папку Tracks в выходную директорию -->
  <ItemGroup>
    <None Include="Tracks\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
  </ItemGroup>
</Project>
